apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  PORT: "3001"
  API_HOST: "http://a62c5a344dc8e49369fa8100916cd0d8-2057603871.ap-south-1.elb.amazonaws.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-test-web
  template:
    metadata:
      labels:
        app: node-test-web
    spec:
      containers:
        - name: node-test-web
          image: soumyaparida00/node-test-web:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
