name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/node-test-web:latest .
          docker push ghcr.io/${{ github.repository }}/node-test-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region

      - name: Install kubectl
        uses: actions-hub/kubectl@v1

      - name: Deploy to EKS
        run: |

          aws eks update-kubeconfig --name node-test-web --region ap-south-1
          kubectl config set-context --current --namespace=reactprod
          kubectl apply -f /home/runner/work/node-test-web/node-test-web/.github/k8s/deployment.yaml
          kubectl apply -f /home/runner/work/node-test-web/node-test-web/.github/k8s/service.yaml
